### ISSUE TITLE
Tooltip crash

### ISSUE THREAD

**Issue by Frzncore** [dannydjdk/Nutritional-Balance#35]
23:03:08.816
net.minecraftforge.eventbus.EventBus
Render thread
23:03:08.817
mezz.jei.library.render.ItemStackRenderer
Render thread
Failed to get tooltip: 1 fried_calamari croptopia:fried_calamari
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:90)
	at TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.__EventTooltip_onItemToolTipEvent_ItemTooltipEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:259)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.item.ItemStack.m_41651_(ItemStack.java:782)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:56)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.library.render.ItemStackRenderer.getTooltip(ItemStackRenderer.java:25)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.common.util.IngredientTooltipHelper.getMutableIngredientTooltipSafe(IngredientTooltipHelper.java:23)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientGridTooltipHelper.getTooltip(IngredientGridTooltipHelper.java:60)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientGridTooltipHelper.drawTooltip(IngredientGridTooltipHelper.java:55)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientGrid.lambda$drawTooltips$4(IngredientGrid.java:179)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientGrid.drawTooltips(IngredientGrid.java:179)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientGridWithNavigation.drawTooltips(IngredientGridWithNavigation.java:246)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.overlay.IngredientListOverlay.drawTooltips(IngredientListOverlay.java:182)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.gui.events.GuiEventHandler.onDrawScreenPost(GuiEventHandler.java:126)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.forge.startup.EventRegistration.lambda$registerGuiHandler$14(EventRegistration.java:113)
	at TRANSFORMER/jei@11.6.0.1018/mezz.jei.core.util.WeakConsumer.accept(WeakConsumer.java:17)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:442)
	at TRANSFORMER/forge@43.3.2/net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.m_239872_(Main.java:212)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.main.Main.main(Main.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.19.2-43.3.2/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
23:03:08.819
com.dannyandson.nutritionalbalance.NutritionalBalance
Render thread
Exception thrown while adding nutrient info  for '   [Fried Calamari]' to tooltips: TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:54)
23:03:09.024
com.dannyandson.nutritionalbalance.NutritionalBalance
Render thread
Exception thrown while adding nutrient info  for '   [Coffee]' to tooltips: TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:54)
23:03:09.026
com.dannyandson.nutritionalbalance.NutritionalBalance
Render thread
Exception thrown while adding nutrient info  for '   [Coffee]' to tooltips: TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:54)
23:03:09.035
com.dannyandson.nutritionalbalance.NutritionalBalance
Render thread
Exception thrown while adding nutrient info  for '   [Coffee]' to tooltips: TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:54)
23:03:09.035
com.dannyandson.nutritionalbalance.NutritionalBalance
Render thread
Exception thrown while adding nutrient info  for '   [Coffee]' to tooltips: TRANSFORMER/nutritionalbalance@1.19.2-4.2.2/com.dannyandson.nutritionalbalance.events.EventTooltip.onItemToolTipEvent(EventTooltip.java:54)
23:03:11.090
net.minecraftforge.eventbus.EventBus
Render thread
23:03:11.090
mezz.jei.library.render.ItemStackRenderer
Render thread
Failed to get tooltip: 1 bat_soup forbidden_arcanus:bat_soup
java.lang.ArrayIndexOutOfBoundsException

[latest.log](https://github.com/dannydjdk/Nutritional-Balance/files/13290055/latest.log)

**Comment by dannydjdk** [comment]
Thank you for the report! Fix has been uploaded to curseforge and should be available soon.
